# -*- coding: utf-8 -*-
"""anomaly-detection-water-pump-system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfRK0MtmCXKBKDiR8lQherg1GjTZRLYX
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pandas as pd
df =  pd.read_csv("sensor.csv")

df.head()

df = df.drop(columns=['Unnamed: 0'])

len(df)

rows_with_zero_or_nan = df.applymap(lambda x: pd.isna(x) ).any(axis=1)  # adding this not changing anything 'or x == 0'
count = rows_with_zero_or_nan.sum()
print(f"Number of rows with at least one 0 or NaN value: {count}")

df.head()

print(df.isnull().sum())

# Drop sensors with excessive missing values
sensors_to_drop = ['sensor_15', 'sensor_50']
df = df.drop(columns=sensors_to_drop)

"""# Maybe KNN for filling data could be better maybe later will check"""

sensor_cols = df.columns[df.isnull().any()].tolist()

print("Columns with at least one NaN value:")
print(sensor_cols)

# Linear interpolation
df[sensor_cols] = df[sensor_cols].interpolate(method='linear')

# If any remaining NaNs, use forward/backward fill
df[sensor_cols] = df[sensor_cols].fillna(method='ffill')
df[sensor_cols] = df[sensor_cols].fillna(method='bfill')
# Verify no missing values remain
print(df[sensor_cols].isnull().sum())

# Convert timestamp to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Encode machine_status if necessary
df['machine_status'] = df['machine_status'].map({'NORMAL': 0, 'BROKEN': 1, 'RECOVERING': 2})

df.info()

"""# I will scale the shit out of my sensors"""

from sklearn.preprocessing import StandardScaler

# Select sensor columns
sensor_cols = [col for col in df.columns if 'sensor_' in col]

# Scale sensor data using StandardScaler
scaler = StandardScaler()
df[sensor_cols] = scaler.fit_transform(df[sensor_cols])

import matplotlib.pyplot as plt

# Plot sensor readings over time for a few sensors
for col in sensor_cols[:3]:
    plt.figure(figsize=(14, 6))
    plt.plot(df['timestamp'], df[col])
    plt.title(f'{col} Over Time')
    plt.xlabel('Timestamp')
    plt.ylabel('Sensor Reading')
    plt.show()

import seaborn as sns

# Compute correlation matrix
corr_matrix = df[sensor_cols].corr()

# Plot heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, cmap='coolwarm')
plt.title('Sensor Correlation Matrix')
plt.show()

# Extract time-based features
df['hour'] = df['timestamp'].dt.hour
df['day_of_week'] = df['timestamp'].dt.dayofweek
df['month'] = df['timestamp'].dt.month

from sklearn.decomposition import PCA

# Apply PCA to sensor data
pca = PCA(n_components=0.99)  # Retain 95% of variance
sensor_data_pca = pca.fit_transform(df[sensor_cols])

# Explained variance ratio
explained_variance = pca.explained_variance_ratio_
print(f'Number of components selected: {pca.n_components_}')
print(f'Explained variance ratio: {sum(explained_variance)}')

# Reconstruct sensor data from PCA components
sensor_data_reconstructed = pca.inverse_transform(sensor_data_pca)

# Calculate reconstruction error
reconstruction_error = ((df[sensor_cols] - sensor_data_reconstructed) ** 2).mean(axis=1)

# Add reconstruction error to DataFrame
df['reconstruction_error'] = reconstruction_error

# Set anomaly threshold (e.g., 95th percentile)
threshold = df['reconstruction_error'].quantile(0.999)

# Flag anomalies
df['anomaly'] = df['reconstruction_error'] > threshold

plt.figure(figsize=(14, 6))
plt.plot(df['timestamp'], df['reconstruction_error'], label='Reconstruction Error')
plt.axhline(y=threshold, color='r', linestyle='--', label='Threshold')
plt.title('Reconstruction Error Over Time')
plt.xlabel('Timestamp')
plt.ylabel('Error')
plt.legend()
plt.show()

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = len(sensor_cols)
encoding_dim = int(input_dim / 2)

input_layer = Input(shape=(input_dim,))
encoder = Dense(encoding_dim, activation='relu')(input_layer)
decoder = Dense(input_dim, activation='sigmoid')(encoder)
autoencoder = Model(inputs=input_layer, outputs=decoder)

autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.summary()

# Prepare data
X = df[sensor_cols].values

# Train model
autoencoder.fit(X, X, epochs=50, batch_size=64, shuffle=True, validation_split=0.1)

import numpy as np
# Reconstruct data
X_pred = autoencoder.predict(X)

# Calculate reconstruction error
mse = np.mean(np.power(X - X_pred, 2), axis=1)
df['reconstruction_error'] = mse

# Set threshold
threshold = np.percentile(mse, 99.9)
df['anomaly'] = df['reconstruction_error'] > threshold

df['anomaly'].value_counts()

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import SMOTE
from collections import Counter
import numpy as np

# Prepare data
X = df[sensor_cols]
y = df['machine_status']

# Encode target variable
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Map encoded classes for clarity
class_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Class Mapping:", class_mapping)

# Check class distribution
unique, counts = np.unique(y_encoded, return_counts=True)
class_distribution = dict(zip(unique, counts))
print("Original Class Distribution:", class_distribution)

# Split data with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, stratify=y_encoded, random_state=42
)

# Recalculate class distribution in y_train
unique_train, counts_train = np.unique(y_train, return_counts=True)
class_distribution_train = dict(zip(unique_train, counts_train))
print("Training Set Class Distribution:", class_distribution_train)

# Determine the minimum number of samples in the minority classes
minority_class_counts = min(counts_train)
print("Minimum samples in minority class:", minority_class_counts)

# Adjust k_neighbors based on minority class samples
k_neighbors = min(5, minority_class_counts - 1)
if k_neighbors < 1:
    k_neighbors = 1  # Set to minimum valid value

print("Adjusted k_neighbors for SMOTE in SMOTEENN:", k_neighbors)

# Create SMOTE instance with adjusted k_neighbors
smote = SMOTE(k_neighbors=k_neighbors, random_state=42)

# Combine over-sampling and under-sampling using SMOTEENN
sme = SMOTEENN(smote=smote, random_state=42)
X_train_resampled, y_train_resampled = sme.fit_resample(X_train, y_train)

# Check the new class distribution
unique_resampled, counts_resampled = np.unique(y_train_resampled, return_counts=True)
class_distribution_resampled = dict(zip(unique_resampled, counts_resampled))
print("Resampled Training Set Class Distribution:", class_distribution_resampled)

# Adjust class weights
from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(y_train_resampled)
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train_resampled
)
class_weight_dict = dict(zip(classes, class_weights))
print("Class Weights:", class_weight_dict)

# Convert class weights to sample weights
sample_weights = np.array([class_weight_dict[label] for label in y_train_resampled])

# Train model with sample weights
model = xgb.XGBClassifier(
    use_label_encoder=False,
    eval_metric='mlogloss',
    random_state=42
)

model.fit(
    X_train_resampled,
    y_train_resampled,
    sample_weight=sample_weights
)

# Predictions
y_pred_proba = model.predict_proba(X_test)

# For multi-class classification, adjust thresholds if necessary
# Here, we will not adjust thresholds but proceed with default argmax
y_pred = np.argmax(y_pred_proba, axis=1)

# Convert class labels to strings for target_names
target_names = [str(class_label) for class_label in le.classes_]

# Evaluate
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=target_names, zero_division=0))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Check the distribution of true and predicted labels
print("\nTrue labels distribution in y_test:", Counter(y_test))
print("Predicted labels distribution in y_pred:", Counter(y_pred))

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Use default base estimator (DecisionTree with max_depth=1)
model = AdaBoostClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

# Train the model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluate
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=target_names, zero_division=0))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print('a')

from sklearn.preprocessing import StandardScaler
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

# Standardize data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[sensor_cols])

# Generate sequences
sequence_length = 10
generator = TimeseriesGenerator(X_scaled, X_scaled, length=sequence_length, batch_size=32)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(sequence_length, len(sensor_cols))))
model.add(Dense(len(sensor_cols)))

model.compile(optimizer='adam', loss='mse')
model.summary()

# Train model
model.fit(generator, epochs=20)

# Generate predictions
X_pred = model.predict(generator)

# Flatten predictions and true values
X_pred_flat = X_pred.reshape(-1, len(sensor_cols))
X_true_flat = X_scaled[sequence_length:]

# Calculate reconstruction error
mse = np.mean(np.power(X_true_flat - X_pred_flat, 2), axis=1)
df['reconstruction_error'] = np.nan
df.loc[df.index[sequence_length:], 'reconstruction_error'] = mse

# Set threshold
threshold = np.percentile(mse, 99.9)
df['anomaly'] = df['reconstruction_error'] > threshold

plt.figure(figsize=(14, 6))
plt.plot(df['timestamp'], df['reconstruction_error'], label='Reconstruction Error')
plt.axhline(y=threshold, color='r', linestyle='--', label='Threshold')
plt.title('LSTM Reconstruction Error Over Time')
plt.xlabel('Timestamp')
plt.ylabel('Error')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Ensure ground truth labels are binary
# Assuming 'machine_status' column exists and maps to NORMAL = 0, BROKEN = 1
y_true = (df['machine_status'] != 0).astype(int)  # Convert to binary (0 = NORMAL, 1 = ANOMALY)

# Predicted labels
y_pred = df['anomaly'].astype(int)

# Generate confusion matrix
cm = confusion_matrix(y_true, y_pred)

# Print confusion matrix
print("Confusion Matrix:")
print(cm)

# Optional: Print classification report
print("\nClassification Report:")
print(classification_report(y_true, y_pred))

# Visualize confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Normal', 'Anomaly'], yticklabels=['Normal', 'Anomaly'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

"""# better lstm

"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, RepeatVector, TimeDistributed, Dense
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix

df['machine_status'].value_counts()

# Assuming df is your DataFrame and sensor_cols are the sensor columns

# Separate normal and anomaly data
normal_data = df[df['machine_status'] == 0]
anomaly_data = df[df['machine_status'] != 0]  # 'BROKEN' or 'RECOVERING'

print(f"Total normal data: {len(normal_data)}")
print(f"Total anomaly data: {len(anomaly_data)}")

# Split normal data into training and validation sets
train_size = int(len(normal_data) * 0.8)
normal_train = normal_data.iloc[:train_size]
normal_val = normal_data.iloc[train_size:]

# Use all anomalies in the validation set
anomaly_val = anomaly_data

# Combine validation data
validation_data = pd.concat([normal_val, anomaly_val])

print(f"Training normal data: {len(normal_train)}")
print(f"Validation normal data: {len(normal_val)}")
print(f"Validation anomaly data: {len(anomaly_val)}")
print(f"Total validation data: {len(validation_data)}")

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(normal_train[sensor_cols])
X_val_scaled = scaler.transform(validation_data[sensor_cols])

def create_sequences(data, seq_length):
    sequences = []
    for i in range(len(data) - seq_length + 1):
        seq = data[i:i+seq_length]
        sequences.append(seq)
    return np.array(sequences)

sequence_length = 10

X_train_seq = create_sequences(X_train_scaled, sequence_length)
X_val_seq = create_sequences(X_val_scaled, sequence_length)

print(f"Training sequences shape: {X_train_seq.shape}")
print(f"Validation sequences shape: {X_val_seq.shape}")

# Get the labels for the validation data
y_val = validation_data['machine_status'].values[sequence_length - 1:]

# Map numeric labels to status names if needed
label_mapping = {0: 'NORMAL', 1: 'BROKEN', 2: 'RECOVERING'}

# Since y_val contains numeric labels, we can use them directly
y_val_labels = y_val  # Already numeric labels

print(f"Validation labels shape: {y_val_labels.shape}")
print("Label distribution in validation data:")

unique, counts = np.unique(y_val_labels, return_counts=True)
label_counts = dict(zip(unique, counts))

for label, count in label_counts.items():
    status = label_mapping[label]
    print(f"{status}: {count}")

timesteps = sequence_length
n_features = X_train_seq.shape[2]

# Define model architecture
inputs = Input(shape=(timesteps, n_features))
encoded = LSTM(64, activation='relu', return_sequences=False)(inputs)
encoded = RepeatVector(timesteps)(encoded)
decoded = LSTM(64, activation='relu', return_sequences=True)(encoded)
decoded = TimeDistributed(Dense(n_features))(decoded)

autoencoder = Model(inputs, decoded)
autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.summary()

def create_sequences(data, sequence_length):
    sequences = []
    for i in range(len(data) - sequence_length):
        seq = data[i:i+sequence_length]
        sequences.append(seq)
    return np.array(sequences)

sequence_length = 10

# Create sequences for training and testing
X_train_seq = create_sequences(X_train, sequence_length)
X_test_seq = create_sequences(X_test, sequence_length)

print("Shape of training sequences:", X_train_seq.shape)
print("Shape of testing sequences:", X_test_seq.shape)

early_stopping = EarlyStopping(
    monitor='val_loss', patience=5, restore_best_weights=True
)

history = autoencoder.fit(
    X_train_seq, X_train_seq,
    epochs=20,
    batch_size=32,
    validation_data=(X_val_seq[y_val_labels == 0], X_val_seq[y_val_labels == 0]),
    callbacks=[early_stopping]
)

# Plot training & validation loss values
plt.figure(figsize=(10, 6))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend()
plt.show()

# Reconstruction errors on training data
X_train_pred = autoencoder.predict(X_train_seq)
train_losses = np.mean(np.abs(X_train_pred - X_train_seq), axis=(1,2))

# Reconstruction errors on validation data
X_val_pred = autoencoder.predict(X_val_seq)
val_losses = np.mean(np.abs(X_val_pred - X_val_seq), axis=(1,2))

mean_train_loss = np.mean(train_losses)
std_train_loss = np.std(train_losses)

# First threshold for severe anomalies ('BROKEN')
threshold_broken = mean_train_loss + 4.5 * std_train_loss

# Second threshold for minor anomalies ('RECOVERING')
threshold_recovering = mean_train_loss + 2 * std_train_loss

print(f"Threshold for 'BROKEN': {threshold_broken}")
print(f"Threshold for 'RECOVERING': {threshold_recovering}")

plt.figure(figsize=(10, 6))
plt.hist(train_losses, bins=50, alpha=0.6, label='Train Losses')
plt.axvline(threshold_recovering, color='orange', linestyle='--', label='Recovering Threshold')
plt.axvline(threshold_broken, color='red', linestyle='--', label='Broken Threshold')
plt.title('Reconstruction Loss Distribution')
plt.xlabel('Loss')
plt.ylabel('Frequency')
plt.legend()
plt.show()

# Initialize predictions array
val_preds = np.zeros(len(val_losses))

# Assign labels based on thresholds
for i, loss in enumerate(val_losses):
    if loss > threshold_broken:
        val_preds[i] = 2  # 'BROKEN'
    elif loss > threshold_recovering and loss < threshold_broken :
        val_preds[i] = 1  # 'RECOVERING'
    else:
        val_preds[i] = 0  # 'NORMAL'

from sklearn.metrics import classification_report, confusion_matrix

# Mapping numerical labels back to status names for report
target_names = ['NORMAL', 'RECOVERING', 'BROKEN']

print("\nClassification Report:")
print(classification_report(y_val_labels, val_preds.astype(int), target_names=target_names, zero_division=0))

print("Confusion Matrix:")
print(confusion_matrix(y_val_labels, val_preds.astype(int)))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Assuming you have already calculated val_losses and have y_val_labels
# y_val_labels contains 0 (NORMAL), 1 (BROKEN), 2 (RECOVERING)

# Create a DataFrame for easy plotting
error_df = pd.DataFrame({
    'Reconstruction_Error': val_losses,
    'Machine_Status': y_val_labels
})

# Map numeric labels to status names for clarity
status_mapping = {0: 'NORMAL', 1: 'BROKEN', 2: 'RECOVERING'}
error_df['Status'] = error_df['Machine_Status'].map(status_mapping)

# Separate the data
broken_errors = error_df[error_df['Status'] == 'BROKEN']['Reconstruction_Error']
recovering_errors = error_df[error_df['Status'] == 'RECOVERING']['Reconstruction_Error']

# Plotting
plt.figure(figsize=(12, 6))
sns.histplot(broken_errors, color='red', label='BROKEN', kde=True, stat="density", linewidth=0)
sns.histplot(recovering_errors, color='orange', label='RECOVERING', kde=True, stat="density", linewidth=0, alpha=0.6)
plt.title('Reconstruction Error Distribution: BROKEN vs. RECOVERING')
plt.xlabel('Reconstruction Error')
plt.ylabel('Density')
plt.legend()
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(x='Status', y='Reconstruction_Error', data=error_df, palette=['green', 'red', 'orange'])
plt.title('Boxplot of Reconstruction Errors by Machine Status')
plt.xlabel('Machine Status')
plt.ylabel('Reconstruction Error')
plt.show()

"""# LSTM for prediction"""

df.head()

sensor_cols = [col for col in df.columns if 'sensor_' in col]
df[sensor_cols].head()

import numpy as np
import pandas as pd
from sklearn.utils import class_weight
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve, precision_recall_curve, average_precision_score
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense
from tensorflow.keras.metrics import Precision, Recall
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import backend as K
import matplotlib.pyplot as plt

label_col = 'machine_status'

# Extract features and labels
data = df[sensor_cols].values  # Shape: (num_samples, num_features)
labels = df[label_col].values  # Shape: (num_samples,)

# Relabel to combine BROKEN and RECOVERING into ANOMALY
labels_binary = np.where(labels == 0, 0, 1)  # 0: NORMAL, 1: ANOMALY

def create_sequences_for_future_prediction(data, labels, seq_length, prediction_horizon):
    X = []
    y = []
    for i in range(len(data) - seq_length - prediction_horizon + 1):
        X_seq = data[i:i+seq_length]
        future_labels = labels[i+seq_length:i+seq_length+prediction_horizon]
        y_label = 1 if 1 in future_labels else 0
        X.append(X_seq)
        y.append(y_label)
    return np.array(X), np.array(y)

sequence_length = 60  # Past 60 time steps
prediction_horizon = 5  # Predict anomalies within the next 5 time steps

X, y = create_sequences_for_future_prediction(data, labels_binary, sequence_length, prediction_horizon)

# Ensure labels are float32
y = y.astype('float32')

# Split the data chronologically
split_ratio = 0.5
split_index = int(len(X) * split_ratio)

X_train, X_val = X[:split_index], X[split_index:]
y_train, y_val = y[:split_index], y[split_index:]

class_weights_array = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)
class_weight_dict = dict(enumerate(class_weights_array))

def f1_score_metric(y_true, y_pred):
    y_true = K.cast(y_true, 'float32')
    y_pred_binary = K.round(y_pred)

    tp = K.sum(y_true * y_pred_binary)
    fp = K.sum((1 - y_true) * y_pred_binary)
    fn = K.sum(y_true * (1 - y_pred_binary))

    precision = tp / (tp + fp + K.epsilon())
    recall = tp / (tp + fn + K.epsilon())

    f1 = 2 * ((precision * recall) / (precision + recall + K.epsilon()))
    return f1

n_features = X_train.shape[2]  # Number of sensor readings

from tensorflow.keras.layers import Dropout

# Example of adding dropout
inputs = Input(shape=(sequence_length, n_features))
x = LSTM(64, activation='relu', return_sequences=True)(inputs)
x = Dropout(0.5)(x)
x = LSTM(32, activation='relu')(x)
outputs = Dense(1, activation='sigmoid')(x)
model = Model(inputs, outputs)



# Compile the model with appropriate loss and metrics
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[Precision(name='precision'), Recall(name='recall'), f1_score_metric]
)

history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_data=(X_val, y_val),
    class_weight=class_weight_dict,  # Apply class weights
    callbacks=[early_stopping],
    verbose=1
)

# Predict probabilities
y_pred_prob = model.predict(X_val)

# Convert probabilities to binary predictions
y_pred = (y_pred_prob > 0.9).astype(int).reshape(-1)

# Classification Report
print("Classification Report:")
print(classification_report(y_val, y_pred, target_names=['NORMAL', 'ANOMALY']))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

# ROC AUC Score
auc = roc_auc_score(y_val, y_pred_prob)
print(f"ROC AUC Score: {auc:.2f}")

len(y_pred)

"""# Precision
NORMAL (Class 0): 1.0
0
Interpretation: When the model predicts a data point as NORMAL, it is 100% correct. There are no false positives for this clas
s.
ANOMALY (Class 1): 0.78
Interpretation: When the model predicts a data point as ANOMALY, it is 78% correct. This means that 22% of the predictions for ANOMALY are false positives (i.e., NORMAL instances incorrectly classified as ANOMALon and recall.

#  Recall
NORMAL (Class 0): 0.98
Interpretation: The model correctly identifies 98% of all actual NORMAL instances. Only 2% of NORMAL instances are missed (i.e., incorrectly classified as ANOMALY).
ANOMALY (Class 1): 0.96
Interpretation: The model correctly identifies 96% of all actual ANOMALY instances. Only 4% of ANOMALY instances are missed (i.e., incorrectly classified as NORMAL).

# F1-Score
NORMAL (Class 0): 0.99
Interpretation: The F1-Score, which balances precision and recall, is 0.99 for NORMAL, indicating excellent performance.
ANOMALY (Class 1): 0.86
Interpretation: The F1-Score for ANOMALY is 0.86, reflecting a strong balance between precision and recall.
"""

# Define sequence parameters
sequence_length = 60
prediction_horizon = 5

# Calculate validation sequence end indices
val_size = len(y_val)  # 44,052
val_start_seq = split_index  # 176,205
val_end_seq = split_index + val_size  # 176,205 + 44,052 = 220,257

# Calculate DataFrame indices corresponding to validation set
sequence_end_indices_val = np.arange(val_start_seq, val_end_seq) + sequence_length + prediction_horizon - 1  # 176,205 to 220,257 +64 = 176,269 to 220,321

# Ensure indices are within DataFrame bounds
sequence_end_indices_val = sequence_end_indices_val[sequence_end_indices_val < len(df)]

print(f"Validation Sequence End Indices: {sequence_end_indices_val[:5]}")
# Ensure 'timestamp' is in datetime format
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Extract corresponding timestamps for validation set
timestamps_val = df['timestamp'].iloc[sequence_end_indices_val].values

# Verify alignment
print(f"Length of timestamps_val: {len(timestamps_val)}")  # Should be 44,052
print(f"Length of y_val: {len(y_val)}")                    # Should be 44,052

# Define your sequence parameters
sequence_length = 60
prediction_horizon = 5

# Calculate the DataFrame indices corresponding to the end of each validation sequence
sequence_end_indices_val = np.arange(split_index, split_index + len(y_val)) + sequence_length + prediction_horizon - 1

# Ensure indices are within DataFrame bounds
sequence_end_indices_val = sequence_end_indices_val[sequence_end_indices_val < len(df)]

# Extract corresponding timestamps
df['timestamp'] = pd.to_datetime(df['timestamp'])  # Ensure 'timestamp' is in datetime format
timestamps_val = df['timestamp'].iloc[sequence_end_indices_val].values

# Verify alignment
print(f"Length of timestamps_val: {len(timestamps_val)}")  # Should match len(y_val)
print(f"Length of y_val: {len(y_val)}")                    # 44,051

sequence_end_indices_val = sequence_end_indices_val[:len(y_val)]

# Define parameters for warning system
consecutive_predictions_required = 3  # Number of consecutive predictions to trigger a warning

# Initialize warnings list
warnings = ['No Warning'] * len(y_val)

# Generate warnings based on consecutive predictions and machine_status
for i in range(len(y_val) - consecutive_predictions_required + 1):
    window = y_val[i:i + consecutive_predictions_required]
    if all(pred == 1 for pred in window):
        # Get the corresponding DataFrame index for the last prediction in the window
        df_index = sequence_end_indices_val[i + consecutive_predictions_required - 1]
        machine_status = df.loc[df_index, 'machine_status']
        if machine_status != 0:
            timestamp = df.loc[df_index, 'timestamp']
            warnings[i + consecutive_predictions_required - 1] = f'Warning: Anomaly Likely at {timestamp}'

# Add warnings to the DataFrame for visualization
# Initialize 'warning' column as 'No Warning' if not already present
if 'warning' not in df.columns:
    df['warning'] = 'No Warning'

# Assign warnings to the corresponding validation indices
df.loc[sequence_end_indices_val, 'warning'] = warnings

# Display the warnings for the first few validation sequences
print(df[['timestamp', 'machine_status', 'warning']].iloc[sequence_end_indices_val].head())

df['warning'].value_counts()



# Define parameters for warning system
consecutive_predictions_required = 3  # Number of consecutive predictions to trigger a warning

# Initialize warnings list
warnings = ['No Warning'] * len(y_val)

# Generate warnings based on consecutive predictions
for i in range(len(y_val) - consecutive_predictions_required + 1):
    window = y_val[i:i + consecutive_predictions_required]
    if all(pred == 1 for pred in window):
        warnings[i + consecutive_predictions_required - 1] = 'Warning: Anomaly Likely'

# Add warnings to the DataFrame for visualization
# Initialize 'warning' column as 'No Warning' if not already present
if 'warning' not in df.columns:
    df['warning'] = 'No Warning'

# Assign 'Warning: Anomaly Likely' to the corresponding validation indices
df.loc[sequence_end_indices_val, 'warning'] = warnings

# Display the warnings for the first few validation sequences
print(df[['timestamp', 'machine_status', 'warning']].iloc[sequence_end_indices_val].head())

df['warning'].value_counts()

# Doğrulama seti DataFrame'i oluştur
df_val = df.iloc[sequence_end_indices_val].copy()

# Etiketleri ekle
df_val['actual_label'] = y_val
df_val['predicted_label'] = y_pred

# 'machine_status' değeri 1 olanları filtrele
df_anomalies = df_val[df_val['machine_status'] != 0]

# Modelin doğru tahmin edip etmediğini kontrol et
df_anomalies['prediction_correct'] = df_anomalies['predicted_label'] == 1

# İlk birkaç sonucu görüntüle
print(df_anomalies[['timestamp', 'machine_status', 'predicted_label', 'prediction_correct']].head())

# Özet istatistikler
num_actual_anomalies = df_anomalies.shape[0]
num_detected_anomalies = df_anomalies['prediction_correct'].sum()
detection_rate = (num_detected_anomalies / num_actual_anomalies) * 100 if num_actual_anomalies > 0 else 0

print(f"Total actual anomalies: {num_actual_anomalies}")
print(f"Total detected anomalies: {num_detected_anomalies}")
print(f"Detection Rate: {detection_rate:.2f}%")

# Parameters
consecutive_predictions_required = 2  # Number of consecutive predictions to trigger a warning

# Initialize warnings list
warnings = ['No Warning'] * len(y_pred)

# Generate warnings based on predictions
for i in range(len(y_pred) - consecutive_predictions_required + 1):
    window = y_pred[i:i+consecutive_predictions_required]
    if all(pred == 1 for pred in window):
        warnings[i + consecutive_predictions_required - 1] = 'Warning: Anomaly Likely'

# Print the warnings for each time step
for idx, warning in enumerate(warnings):
    if warning == 'Warning: Anomaly Likely':
        print(f"Time Step {idx}: {warning}")

import matplotlib.pyplot as plt

# Görselleştirme
plt.figure(figsize=(15,6))
plt.plot(timestamps_val, y_val, label='Actual Anomalies', color='blue', alpha=0.6)

# Uyarıları renklendir
warning_colors = {'No Warning': 'grey', 'Warning: Anomaly Likely at': 'red'}
warning_colors_mapped = ['red' if 'Warning' in warn else 'grey' for warn in warnings]

# Uyarıları işaretle
plt.scatter(timestamps_val, y_val, c=warning_colors_mapped, marker='x', label='Warnings')

# İsteğe bağlı: Uyarıları anotasyonla işaretle
for i, warn in enumerate(warnings):
    if 'Warning' in warn:
        plt.annotate('Warning', (timestamps_val[i], y_val[i]),
                     textcoords="offset points", xytext=(0,10), ha='center', color='red')

plt.title('Anomaly Detection with Warnings')
plt.xlabel('Timestamp')
plt.ylabel('Anomaly Status')
plt.legend(['Actual Anomalies', 'Warnings'])
plt.show()

# Visualize warnings alongside actual anomalies
plt.figure(figsize=(15,6))
plt.plot(y_val, label='Actual Anomalies', color='blue', alpha=0.6)

# Map warnings to colors
warning_colors = {'No Warning': 'grey', 'Warning: Anomaly Likely': 'red'}
warning_colors_mapped = [warning_colors[warn] for warn in warnings]

# Plot warnings
plt.scatter(range(len(warnings)), y_val, c=warning_colors_mapped, marker='x', label='Warnings')

plt.title('Anomaly Detection with Warnings')
plt.xlabel('Time Steps')
plt.ylabel('Anomaly Status')
plt.legend(['Actual Anomalies', 'Warnings'])
plt.show()