# -*- coding: utf-8 -*-
"""anomaly-detection-water-pump-system-transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfRK0MtmCXKBKDiR8lQherg1GjTZRLYX
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

def main():
    # Set device for GPU usage with better configuration
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")
        print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.2f} GB")
        
        # Enable TF32 for faster training on modern GPUs
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True

    # Load data
    df = pd.read_csv("sensor.csv")
    df = df.drop(columns=['Unnamed: 0'])

    # Data cleaning
    print("Data cleaning...")
    sensors_to_drop = ['sensor_15', 'sensor_50']
    df = df.drop(columns=sensors_to_drop)

    # Handle missing values
    sensor_cols = [col for col in df.columns if 'sensor_' in col]
    df[sensor_cols] = df[sensor_cols].interpolate(method='linear')
    df[sensor_cols] = df[sensor_cols].fillna(method='ffill')
    df[sensor_cols] = df[sensor_cols].fillna(method='bfill')

    # Preprocessing
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['machine_status'] = df['machine_status'].map({'NORMAL': 0, 'BROKEN': 1, 'RECOVERING': 2})

    # Scale sensor data
    scaler = StandardScaler()
    df[sensor_cols] = scaler.fit_transform(df[sensor_cols])

    # Time-based features
    df['hour'] = df['timestamp'].dt.hour
    df['day_of_week'] = df['timestamp'].dt.dayofweek
    df['month'] = df['timestamp'].dt.month

    print("Data preprocessing completed!")

    # Transformer-based Anomaly Detection Model
    class TimeSeriesTransformer(nn.Module):
        def __init__(self, num_sensors, d_model=128, nhead=8, num_layers=4, dropout=0.1):
            super(TimeSeriesTransformer, self).__init__()
            
            self.device = device
            self.input_projection = nn.Linear(num_sensors, d_model)
            
            # Transformer encoder
            encoder_layer = nn.TransformerEncoderLayer(
                d_model=d_model,
                nhead=nhead,
                dim_feedforward=d_model * 4,
                dropout=dropout,
                batch_first=True,
                activation='gelu'  # Better activation for transformers
            )
            self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
            
            # Reconstruction head
            self.reconstruction_head = nn.Sequential(
                nn.Linear(d_model, d_model // 2),
                nn.GELU(),
                nn.Dropout(dropout),
                nn.Linear(d_model // 2, num_sensors)
            )
            
            # Anomaly classification head - REMOVE SIGMOID for BCEWithLogitsLoss
            self.anomaly_head = nn.Sequential(
                nn.Linear(d_model, d_model // 2),
                nn.GELU(),
                nn.Dropout(dropout),
                nn.Linear(d_model // 2, 1)
                # Sigmoid removed - will be handled by BCEWithLogitsLoss
            )
            
            # Initialize weights
            self.apply(self._init_weights)
            
        def _init_weights(self, module):
            if isinstance(module, nn.Linear):
                torch.nn.init.xavier_uniform_(module.weight)
                if module.bias is not None:
                    torch.nn.init.constant_(module.bias, 0)
                    
        def forward(self, x, return_attention=False):
            # x shape: (batch_size, seq_len, num_sensors)
            x = self.input_projection(x)
            
            # Transformer encoding
            encoded = self.transformer_encoder(x)
            
            # Use last timestep for classification
            last_timestep = encoded[:, -1, :]
            
            # Reconstruction
            reconstructed = self.reconstruction_head(encoded)
            
            # Anomaly detection - return logits (no sigmoid)
            anomaly_logits = self.anomaly_head(last_timestep)
            
            if return_attention:
                return reconstructed, anomaly_logits, encoded
            return reconstructed, anomaly_logits

    # Dataset class with GPU optimizations
    class SensorDataset(Dataset):
        def __init__(self, data, sensor_cols, sequence_length=60, target_col='machine_status', prediction_horizon=5):
            self.data = data
            self.sensor_cols = sensor_cols
            self.sequence_length = sequence_length
            self.prediction_horizon = prediction_horizon
            
            # Pre-allocate arrays for better performance
            data_length = len(data) - sequence_length - prediction_horizon + 1
            self.sequences = np.zeros((data_length, sequence_length, len(sensor_cols)), dtype=np.float32)
            self.labels = np.zeros((data_length, 1), dtype=np.float32)
            
            # Create sequences
            sensor_data = data[sensor_cols].values.astype(np.float32)
            target_data = data[target_col].values
            
            for i in range(data_length):
                seq_data = sensor_data[i:i+sequence_length]
                future_status = target_data[i+sequence_length:i+sequence_length+prediction_horizon]
                
                # Binary label: 1 if any anomaly in future horizon, 0 otherwise
                label = 1.0 if any(status != 0 for status in future_status) else 0.0
                
                self.sequences[i] = seq_data
                self.labels[i] = label
        
        def __len__(self):
            return len(self.sequences)
        
        def __getitem__(self, idx):
            # Return tensors directly
            sequence = torch.from_numpy(self.sequences[idx])
            label = torch.from_numpy(self.labels[idx])
            return sequence, label

    # Training function with comprehensive GPU optimization
    def train_transformer_model(model, train_loader, val_loader, num_epochs=50, learning_rate=1e-4):
        # Move model to GPU immediately
        model = model.to(device, non_blocking=True)
        print(f"Model moved to: {next(model.parameters()).device}")
        
        optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)
        
        reconstruction_criterion = nn.MSELoss()
        classification_criterion = nn.BCEWithLogitsLoss()  # Changed from BCELoss
        
        train_losses = []
        val_losses = []
        
        # Use mixed precision for faster training on GPU
        scaler = torch.cuda.amp.GradScaler() if torch.cuda.is_available() else None
        
        # Pre-allocate for validation to reduce memory fragmentation
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        
        for epoch in range(num_epochs):
            # Training
            model.train()
            train_loss = 0
            train_samples = 0
            
            train_iterator = tqdm(train_loader, desc=f'Epoch {epoch+1}/{num_epochs}')
            for batch_seq, batch_labels in train_iterator:
                batch_seq = batch_seq.to(device, non_blocking=True)
                batch_labels = batch_labels.to(device, non_blocking=True)
                
                optimizer.zero_grad(set_to_none=True)  # Faster zero_grad
                
                if scaler is not None:
                    # Use mixed precision
                    with torch.cuda.amp.autocast():
                        reconstructed, anomaly_logits = model(batch_seq)
                        
                        # Combined loss
                        recon_loss = reconstruction_criterion(reconstructed, batch_seq)
                        class_loss = classification_criterion(anomaly_logits, batch_labels)
                        loss = recon_loss + class_loss
                    
                    scaler.scale(loss).backward()
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    reconstructed, anomaly_logits = model(batch_seq)
                    
                    # Combined loss
                    recon_loss = reconstruction_criterion(reconstructed, batch_seq)
                    class_loss = classification_criterion(anomaly_logits, batch_labels)
                    loss = recon_loss + class_loss
                    
                    loss.backward()
                    optimizer.step()
                
                train_loss += loss.item() * batch_seq.size(0)
                train_samples += batch_seq.size(0)
                train_iterator.set_postfix({'Loss': f'{loss.item():.4f}'})
            
            avg_train_loss = train_loss / train_samples
            train_losses.append(avg_train_loss)
            
            # Validation
            model.eval()
            val_loss = 0
            val_samples = 0
            all_preds = []
            all_labels = []
            
            with torch.no_grad():
                for batch_seq, batch_labels in val_loader:
                    batch_seq = batch_seq.to(device, non_blocking=True)
                    batch_labels = batch_labels.to(device, non_blocking=True)
                    
                    if scaler is not None:
                        with torch.cuda.amp.autocast():
                            reconstructed, anomaly_logits = model(batch_seq)
                            
                            recon_loss = reconstruction_criterion(reconstructed, batch_seq)
                            class_loss = classification_criterion(anomaly_logits, batch_labels)
                            loss = recon_loss + class_loss
                    else:
                        reconstructed, anomaly_logits = model(batch_seq)
                        
                        recon_loss = reconstruction_criterion(reconstructed, batch_seq)
                        class_loss = classification_criterion(anomaly_logits, batch_labels)
                        loss = recon_loss + class_loss
                    
                    val_loss += loss.item() * batch_seq.size(0)
                    val_samples += batch_seq.size(0)
                    
                    # Convert logits to probabilities for evaluation
                    anomaly_probs = torch.sigmoid(anomaly_logits)
                    all_preds.extend(anomaly_probs.cpu().numpy())
                    all_labels.extend(batch_labels.cpu().numpy())
            
            avg_val_loss = val_loss / val_samples
            val_losses.append(avg_val_loss)
            
            scheduler.step()
            
            print(f'Epoch {epoch+1}: Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}, LR: {scheduler.get_last_lr()[0]:.2e}')
            
            # Early stopping condition
            if epoch > 10 and avg_val_loss > min(val_losses[-5:]):
                print("Early stopping triggered!")
                break
        
        # Clear GPU cache
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        
        return model, train_losses, val_losses

    # Prepare data for transformer
    print("Preparing data for transformer model...")

    # Create binary labels for anomaly detection
    df['anomaly_binary'] = (df['machine_status'] != 0).astype(int)

    # Split data chronologically
    split_idx = int(len(df) * 0.7)
    train_df = df.iloc[:split_idx]
    val_df = df.iloc[split_idx:]

    # Create datasets
    sequence_length = 60
    prediction_horizon = 5

    train_dataset = SensorDataset(train_df, sensor_cols, sequence_length, 'anomaly_binary', prediction_horizon)
    val_dataset = SensorDataset(val_df, sensor_cols, sequence_length, 'anomaly_binary', prediction_horizon)

    # Create data loaders with optimized settings for GPU
    # For Windows, use 0 workers to avoid multiprocessing issues
    batch_size = 64 if torch.cuda.is_available() else 32
    num_workers = 0  # Set to 0 for Windows to avoid multiprocessing issues
    pin_memory = torch.cuda.is_available()

    train_loader = DataLoader(
        train_dataset, 
        batch_size=batch_size, 
        shuffle=True,
        num_workers=num_workers,
        pin_memory=pin_memory
    )
    val_loader = DataLoader(
        val_dataset, 
        batch_size=batch_size, 
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory
    )

    print(f"Training samples: {len(train_dataset)}")
    print(f"Validation samples: {len(val_dataset)}")
    print(f"Batch size: {batch_size}")
    print(f"Using {num_workers} workers with pin_memory={pin_memory}")

    # Initialize and train transformer model
    print("Initializing Transformer model...")
    model = TimeSeriesTransformer(
        num_sensors=len(sensor_cols),
        d_model=128,
        nhead=8,
        num_layers=4,
        dropout=0.1
    )

    # Print model summary and move to GPU
    print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")
    print("Training Transformer model...")

    # Clear GPU cache before training
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    trained_model, train_losses, val_losses = train_transformer_model(
        model, train_loader, val_loader, num_epochs=50, learning_rate=1e-4
    )

    # Plot training history
    plt.figure(figsize=(10, 6))
    plt.plot(train_losses, label='Training Loss')
    plt.plot(val_losses, label='Validation Loss')
    plt.title('Transformer Training History')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.show()

    # Evaluation function with GPU optimization
    def evaluate_model(model, data_loader):
        model.eval()
        
        all_preds = []
        all_labels = []
        reconstruction_errors = []
        
        with torch.no_grad():
            for batch_seq, batch_labels in data_loader:
                batch_seq = batch_seq.to(device, non_blocking=True)
                batch_labels = batch_labels.to(device, non_blocking=True)
                
                if torch.cuda.is_available():
                    with torch.cuda.amp.autocast():
                        reconstructed, anomaly_logits = model(batch_seq)
                else:
                    reconstructed, anomaly_logits = model(batch_seq)
                
                # Convert logits to probabilities
                anomaly_probs = torch.sigmoid(anomaly_logits)
                
                # Calculate reconstruction error
                recon_error = torch.mean((reconstructed - batch_seq) ** 2, dim=(1, 2))
                
                all_preds.extend(anomaly_probs.cpu().numpy())
                all_labels.extend(batch_labels.cpu().numpy())
                reconstruction_errors.extend(recon_error.cpu().numpy())
        
        return np.array(all_preds), np.array(all_labels), np.array(reconstruction_errors)

    # Evaluate the model
    print("Evaluating model...")
    val_preds, val_labels, val_recon_errors = evaluate_model(trained_model, val_loader)

    # Fix: Ensure val_labels is 1D for indexing
    val_labels = val_labels.flatten()  # Convert to 1D array
    val_preds = val_preds.flatten()    # Ensure predictions are also 1D

    # Convert probabilities to binary predictions
    threshold = 0.5
    val_preds_binary = (val_preds > threshold).astype(int)

    # Print evaluation metrics
    print("\nClassification Report:")
    print(classification_report(val_labels, val_preds_binary, target_names=['Normal', 'Anomaly']))

    print("\nConfusion Matrix:")
    print(confusion_matrix(val_labels, val_preds_binary))

    auc_score = roc_auc_score(val_labels, val_preds)
    print(f"\nROC AUC Score: {auc_score:.4f}")

    # Advanced anomaly detection with reconstruction error
    combined_scores = 0.7 * val_preds.flatten() + 0.3 * (val_recon_errors / np.max(val_recon_errors))
    combined_threshold = np.percentile(combined_scores, 95)
    combined_predictions = (combined_scores > combined_threshold).astype(int)

    print("\nCombined Reconstruction + Classification Results:")
    print(classification_report(val_labels, combined_predictions, target_names=['Normal', 'Anomaly']))

    # Visualization - FIXED: Now using 1D arrays for indexing
    plt.figure(figsize=(15, 10))

    # Plot 1: Anomaly scores distribution
    plt.subplot(2, 2, 1)
    plt.hist(val_preds[val_labels == 0], bins=50, alpha=0.7, label='Normal', color='green')
    plt.hist(val_preds[val_labels == 1], bins=50, alpha=0.7, label='Anomaly', color='red')
    plt.axvline(threshold, color='black', linestyle='--', label=f'Threshold ({threshold})')
    plt.title('Anomaly Scores Distribution')
    plt.xlabel('Anomaly Score')
    plt.ylabel('Frequency')
    plt.legend()

    # Plot 2: Reconstruction errors - FIXED: Using 1D val_labels
    plt.subplot(2, 2, 2)
    plt.hist(val_recon_errors[val_labels == 0], bins=50, alpha=0.7, label='Normal', color='green')
    plt.hist(val_recon_errors[val_labels == 1], bins=50, alpha=0.7, label='Anomaly', color='red')
    plt.title('Reconstruction Errors Distribution')
    plt.xlabel('Reconstruction Error')
    plt.ylabel('Frequency')
    plt.legend()

    # Plot 3: ROC curve
    from sklearn.metrics import roc_curve
    fpr, tpr, _ = roc_curve(val_labels, val_preds)
    plt.subplot(2, 2, 3)
    plt.plot(fpr, tpr, label=f'Transformer (AUC = {auc_score:.3f})')
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve')
    plt.legend()

    # Plot 4: Precision-Recall curve
    from sklearn.metrics import precision_recall_curve, average_precision_score
    precision, recall, _ = precision_recall_curve(val_labels, val_preds)
    avg_precision = average_precision_score(val_labels, val_preds)
    plt.subplot(2, 2, 4)
    plt.plot(recall, precision, label=f'Transformer (AP = {avg_precision:.3f})')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.title('Precision-Recall Curve')
    plt.legend()

    plt.tight_layout()
    plt.show()

    # Real-time prediction function with GPU optimization
    def predict_anomaly(model, sensor_data, threshold=0.5):
        """
        Predict anomaly for real-time sensor data
        """
        model.eval()
        
        with torch.no_grad():
            sensor_tensor = torch.FloatTensor(sensor_data).unsqueeze(0)
            sensor_tensor = sensor_tensor.to(device, non_blocking=True)
            
            if torch.cuda.is_available():
                with torch.cuda.amp.autocast():
                    reconstructed, anomaly_logits = model(sensor_tensor)
            else:
                reconstructed, anomaly_logits = model(sensor_tensor)
            
            # Convert logits to probabilities
            anomaly_probs = torch.sigmoid(anomaly_logits)
            
            is_anomaly = anomaly_probs.item() > threshold
            confidence = anomaly_probs.item()
            
            # Calculate reconstruction error
            recon_error = torch.mean((reconstructed - sensor_tensor) ** 2).item()
        
        return is_anomaly, confidence, recon_error

    # Example usage for real-time prediction
    print("\nReal-time Prediction Example:")
    sample_sequence = val_dataset[0][0].numpy()  # Get a sample sequence
    is_anomaly, confidence, recon_error = predict_anomaly(trained_model, sample_sequence)

    print(f"Anomaly Detected: {is_anomaly}")
    print(f"Confidence: {confidence:.4f}")
    print(f"Reconstruction Error: {recon_error:.4f}")

    # Save model (move to CPU first for compatibility)
    trained_model_cpu = trained_model.to('cpu')
    torch.save({
        'model_state_dict': trained_model_cpu.state_dict(),
        'sensor_cols': sensor_cols,
        'scaler': scaler,
        'sequence_length': sequence_length
    }, 'transformer_anomaly_detector.pth')

    # Move back to GPU if needed for further operations
    trained_model.to(device)
    print("\nModel saved as 'transformer_anomaly_detector.pth'")

    # Warning system implementation with GPU optimization
    def implement_warning_system(model, data_loader, consecutive_warnings=3):
        """
        Implement a warning system that triggers after consecutive anomalies
        """
        model.eval()
        
        warnings = []
        anomaly_buffer = []
        
        with torch.no_grad():
            for batch_seq, batch_labels in data_loader:
                batch_seq = batch_seq.to(device, non_blocking=True)
                
                if torch.cuda.is_available():
                    with torch.cuda.amp.autocast():
                        reconstructed, anomaly_logits = model(batch_seq)
                else:
                    reconstructed, anomaly_logits = model(batch_seq)
                
                # Convert logits to probabilities
                anomaly_probs = torch.sigmoid(anomaly_logits)
                batch_predictions = (anomaly_probs.cpu().numpy() > 0.5).astype(int).flatten()
                
                for pred in batch_predictions:
                    anomaly_buffer.append(pred)
                    
                    # Keep only recent predictions
                    if len(anomaly_buffer) > consecutive_warnings:
                        anomaly_buffer.pop(0)
                    
                    # Check for consecutive anomalies
                    if len(anomaly_buffer) == consecutive_warnings and all(anomaly_buffer):
                        warnings.append("🚨 CRITICAL: Consecutive anomalies detected!")
                    elif pred == 1:
                        warnings.append("⚠️ Warning: Anomaly detected")
                    else:
                        warnings.append("✅ Normal operation")
        
        return warnings

    # Generate warnings
    print("\nGenerating warnings...")
    sample_warnings = implement_warning_system(trained_model, val_loader)
    for i, warning in enumerate(sample_warnings[:20]):  # Show first 20 warnings
        print(f"Step {i+1}: {warning}")

    # Final GPU memory cleanup and performance report
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        print(f"\nFinal GPU memory allocated: {torch.cuda.memory_allocated(0) / 1024**2:.2f} MB")
        print(f"Peak GPU memory allocated: {torch.cuda.max_memory_allocated(0) / 1024**2:.2f} MB")
        print(f"GPU utilization completed successfully!")

if __name__ == '__main__':
    main()